from __future__ import annotations

import base64
from dataclasses import dataclass

import httpx

from repopilot.config import Settings
from repopilot.models import FileEdit
from repopilot.security import SecurityError, validate_branch, validate_repository_url


@dataclass(slots=True)
class PublishResult:
    published: bool
    pull_request_url: str | None = None
    branch: str | None = None
    reason: str | None = None


class GitHubPublisher:
    """A narrowly scoped GitHub REST tool, invoked only after HITL approval."""

    def __init__(self, settings: Settings):
        self.settings = settings

    async def publish(
        self,
        *,
        task_id: str,
        repository_url: str,
        base_branch: str,
        issue_title: str,
        edits: list[FileEdit],
    ) -> PublishResult:
        if repository_url.startswith("demo://"):
            return PublishResult(published=False, reason="Demo runs never write to GitHub")
        if not self.settings.github_write_enabled:
            return PublishResult(published=False, reason="GitHub writes are disabled")
        if not self.settings.github_token:
            return PublishResult(published=False, reason="GITHUB_TOKEN is not configured")

        owner, repo = validate_repository_url(repository_url)
        if owner.lower() not in self.settings.allowed_github_owners:
            raise SecurityError(f"GitHub owner is not allowlisted: {owner}")
        validate_branch(base_branch)
        branch = f"repopilot/{task_id[:8]}"
        headers = {
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {self.settings.github_token}",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        api = f"https://api.github.com/repos/{owner}/{repo}"
        async with httpx.AsyncClient(headers=headers, timeout=30) as client:
            base_ref = await self._json(client, "GET", f"{api}/git/ref/heads/{base_branch}")
            base_sha = base_ref["object"]["sha"]
            base_commit = await self._json(client, "GET", f"{api}/git/commits/{base_sha}")
            tree_entries: list[dict[str, str]] = []
            for edit in edits:
                blob = await self._json(
                    client,
                    "POST",
                    f"{api}/git/blobs",
                    json={
                        "content": base64.b64encode(edit.content.encode()).decode(),
                        "encoding": "base64",
                    },
                )
                tree_entries.append(
                    {"path": edit.path, "mode": "100644", "type": "blob", "sha": blob["sha"]}
                )
            tree = await self._json(
                client,
                "POST",
                f"{api}/git/trees",
                json={"base_tree": base_commit["tree"]["sha"], "tree": tree_entries},
            )
            commit = await self._json(
                client,
                "POST",
                f"{api}/git/commits",
                json={
                    "message": f"fix: {issue_title}",
                    "tree": tree["sha"],
                    "parents": [base_sha],
                },
            )
            await self._json(
                client,
                "POST",
                f"{api}/git/refs",
                json={"ref": f"refs/heads/{branch}", "sha": commit["sha"]},
            )
            pull = await self._json(
                client,
                "POST",
                f"{api}/pulls",
                json={
                    "title": f"[RepoPilot] {issue_title}",
                    "head": branch,
                    "base": base_branch,
                    "body": (
                        "Generated by RepoPilot after tests, reviewer verification, "
                        "and human approval."
                    ),
                    "draft": True,
                },
            )
        return PublishResult(published=True, pull_request_url=pull["html_url"], branch=branch)

    @staticmethod
    async def _json(
        client: httpx.AsyncClient,
        method: str,
        url: str,
        *,
        json: dict[str, object] | None = None,
    ) -> dict[str, object]:
        response = await client.request(method, url, json=json)
        response.raise_for_status()
        return response.json()
